name: run-tests

on: [push, pull_request]

jobs:
    test:
        strategy:
            fail-fast: true
            matrix:
                php: [8.0, 8.1, 8.2]
                laravel: [^8.80, 9.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 9.*
                        testbench: 7.*
                    -   laravel: ^8.80
                        testbench: 6.23
                exclude:
                    -   laravel: ^8.80
                        php: 8.2

        runs-on: ubuntu-latest
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, mbstring, libxml, pdo, sqlite, pdo_sqlite
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            -   name: Execute tests
                run: vendor/bin/phpunit
